### ISSUE TITLE
Conventions around no_std

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-api-guidelines#23]

**Comment by dtolnay** [comment]
Including what the `std` feature should be called if there is one. https://github.com/rust-lang-nursery/log/issues/176

**Comment by Kixunil** [comment]
I'd prefer `with_std`, since simple `std` might suggest that it's some sort of "standard feature". Or maybe `with_std_lib` to be very clear from first glance.

Alternatively use `use` instead of `with`. :) I'm not a native speaker so I'm not sure which would be more appropriate.

**Comment by dtolnay** [comment]
I strongly prefer `std` over `with_std` or `use_std`.

It aligns better with the optional dependency / implicit feature mechanism. If you have an optional dependency on `serde`, the implicit feature is called `serde` not `with_serde` or `use_serde`.

**Comment by Kixunil** [comment]
Ah, good point, I completely forgot about that.

Bit OT idea: provide a way to create documentation for features? e.g.

```
## Enables features from std crate
std = []
```

Maybe with default doc string for implicit features? That would seem to me like the best of both worlds.

**Comment by tarcieri** [comment]
I've generally gone with "std" for my own projects, however I've seen a decent amount of "use_std"

**Comment by dtolnay** [comment]
Added in a15e953eace73b10759824a6fc7e703afd724f8c.

**Comment by Kixunil** [comment]
I guess I'll have to rewrite some stuff but I agree with the decision.
