### ISSUE TITLE
Guidelines for changelogs / release notes

### ISSUE THREAD

**Issue by mbrubeck** [brson/rust-api-guidelines#3]
Release notes or change logs are very useful!  Some suggested guidelines:

* Include release notes in your top-level documentation or in a location linked from your top-level documentation.
* Include an entry in the release notes for every published version of every crate.  Include the date the version was released.  Optional: Link to specific tags or revisions in your version control repository.
* Changes that may break downstream code should be marked with the text `[breaking change]`.

The rationale for these guidelines is to make it easy for users of your crate to know what to expect when upgrading to a new version of your crate, or to determine what version introduced a specific change.

**Comment by mbrubeck** [comment]
Note: Making Cargo and/or crates.io aware of change logs might be an alternative to the first guideline (e.g. rust-lang/cargo#1369).

**Comment by dtolnay** [comment]
I would strongly prefer not to use a release notes file in my crates. Instead I have been using tagged releases - for example see [serde releases](https://github.com/serde-rs/serde/releases) and [serde_json releases](https://github.com/serde-rs/json/releases). A major advantage is that release notes are automatically emailed out to watchers when I tag a release and appear in their github dashboard.

**Comment by mbrubeck** [comment]
Good point. The guidelines should be flexible and not specify where/how the release notes are stored.  The important thing is that users have a place to view the change log, and a way to find it.
