### ISSUE TITLE
Convention around fn new() vs. impl Default

### ISSUE THREAD

**Issue by killercup** [brson/rust-api-guidelines#38]
C-COMMON-TRAITS wants me to `impl Default`. The first example in C-CTOR is `fn new() -> Example<T>`.

It would be nice to have a convention around when a `new` constructor with no parameters makes sense, when we should just use `Default::default`, and when `new` should actually use `default` (or some other variations).

Previous discussions about this:

- https://github.com/rust-unofficial/patterns/pull/48
- https://deterministic.space/elegant-apis-in-rust.html#fn:new
- https://github.com/killercup/scribbles/commit/c5863ebdbf343e14d0b5f9e25633ceac6945a41f#commitcomment-19523203
- https://github.com/killercup/scribbles/commit/628f5310cbb601a141dca1dfb057508c9460b006#commitcomment-19527945

cc @llogiq

**Comment by brson** [comment]
Clarify that if you can have a 'new' ctor it should exist, and do the same as 'default'. Add to `C-CTOR`.

**Comment by llogiq** [comment]
Note that a `new` ctor is easier to find in the docs (and to document specifics for) than a `Default` impl. So even if the latter exists, it makes sense to provide the former.

**Comment by killercup** [comment]
> Note that a new ctor is easier to find in the docs

Will put this on my 'Rustdoc2 features wish list'! (It's getting longer every day.)
