### ISSUE TITLE
Mention HashMap::insert and HashSet::insert under c-intermediate

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-api-guidelines#55]
These are good examples of handing back ownership and returning useful information to avoid duplicate work.

**Comment by brson** [comment]
Just add as an example, following existing such examples.

**Comment by dowoncha** [comment]
Should examples be added only for HashMap/HashSet::insert or the Vec::binary_search and String::from_utf8 as well?

**Comment by brson** [comment]
@dowoncha They all seem worth mentioning. I believe this issue is just to mention and link to these types as examples. Don't need to actually write code examples.
