### ISSUE TITLE
C-GENERIC should mention IntoInterator instead of Iterator

### ISSUE THREAD

**Issue by yoanlcq** [brson/rust-api-guidelines#56]
This snippet from [C-GENERIC](https://github.com/brson/rust-api-guidelines#c-generic)
```rust
fn foo<I: Iterator<Item = i64>>(iter: I) { /* ... */ }
```
should read instead
```rust
fn foo<I: IntoIterator<Item = i64>>(iter: I) { /* ... */ }
```
Because it minimizes assumptions even more. A good example here would be [the `extend()` method](https://doc.rust-lang.org/std/iter/trait.Extend.html#tymethod.extend) provided by the `std::iter::Extend` trait.

**Comment by brson** [comment]
Seems correct.
