### ISSUE TITLE
Guideline updates based on the reqwest evaluation

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-api-guidelines#62]
What lessons can we learn from `reqwest` that will be broadly applicable to other crates? Please leave a comment with your ideas!

[*Crate evaluation thread on internals.rust-lang.org*](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-30-reqwest/5248)

**Comment by KodrAus** [comment]
A few things I like about `reqwest`s design so far:

- Explicitly [ensuring certain types implement traits](https://github.com/seanmonstar/reqwest/blob/241e5069b4e5935a3aac470c5b4d3b8b5b8f6714/src/lib.rs#L174-L189) so they don't accidentally regress
- The [approach to error handling](https://github.com/seanmonstar/reqwest/blob/241e5069b4e5935a3aac470c5b4d3b8b5b8f6714/src/error.rs) is quite nice. Errors are opaque, so tweaking them isn't always a breaking change and they contain extra useful information. I think it would be nice if projects like `error-chain` supported black-box errors of this kind too. Locking down the public API seems like a bit of a prerequisite for a stable release.
