### ISSUE TITLE
Reconsider the C-CI requirement

### ISSUE THREAD

**Issue by ishitatsuyuki** [brson/rust-api-guidelines#74]
Link for lazy people: https://github.com/brson/rust-api-guidelines#c-ci

I have much hate for CI badges, because they essentially does nothing. It doesn't show the status of released tag, it doesn't make anything working magically when a build fails. It doesn't prove that you have well written tests too. **It just makes it easy to merge a PR confidently.**

> Stable, high-profile crates should meet the same level of rigor when it comes to tier 1. To prove it, Cargo.toml should publish CI badges.

If we're achieving the same thing as rust-lang/rust, we **shouldn't** publish the badges. The compiler repo doesn't show any badges at all.

Instead, we should just make sure CI is set up. Quoting https://github.com/Manishearth/rust-clippy/issues/1792#issuecomment-304476008, CI badges are a type of lock-in, and we shouldn't force the maintainer to do so.

**Comment by Kixunil** [comment]
Requiring badges seems ridiculous to me too.

**Comment by dtolnay** [comment]
Removed in a06646c02937e62a949a13850d278c09b79c0f07.
